# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DQPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
pod 'Masonry', '~> 1.0.2'
pod 'YYModel', '~> 1.0.4'


  # use_frameworks!

  # Pods for DQPlayer

end
